// ============================================
// Enums (mirroring Prisma enums for frontend use)
// ============================================

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  GYM_MANAGER = 'GYM_MANAGER',
  RECEPTIONIST = 'RECEPTIONIST',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum MemberStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  DELETED = 'DELETED',
}

export enum MembershipStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  FROZEN = 'FROZEN',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
}

export enum PlanDuration {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  HALF_YEARLY = 'HALF_YEARLY',
  YEARLY = 'YEARLY',
}

export enum PaymentMethod {
  CASH = 'CASH',
  CARD = 'CARD',
  BANK = 'BANK',
  ONLINE = 'ONLINE',
}

export enum PaymentStatus {
  PAID = 'PAID',
  PARTIAL = 'PARTIAL',
  PENDING = 'PENDING',
  REFUNDED = 'REFUNDED',
}

export enum DeviceConnectionType {
  ETHERNET = 'ETHERNET',
  WIFI = 'WIFI',
}

export enum DeviceStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}

export enum SyncAction {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  ENABLE_USER = 'ENABLE_USER',
  DISABLE_USER = 'DISABLE_USER',
  DOWNLOAD_ATTENDANCE = 'DOWNLOAD_ATTENDANCE',
  SYNC_USERS = 'SYNC_USERS',
}

export enum SyncJobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum AccessResult {
  GRANTED = 'GRANTED',
  DENIED = 'DENIED',
}

export enum AccessDenyReason {
  MEMBERSHIP_EXPIRED = 'MEMBERSHIP_EXPIRED',
  MEMBERSHIP_SUSPENDED = 'MEMBERSHIP_SUSPENDED',
  MEMBERSHIP_FROZEN = 'MEMBERSHIP_FROZEN',
  UNKNOWN_USER = 'UNKNOWN_USER',
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  MANUAL_BLOCK = 'MANUAL_BLOCK',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  MEMBER_CREATED = 'MEMBER_CREATED',
  MEMBER_UPDATED = 'MEMBER_UPDATED',
  MEMBER_DELETED = 'MEMBER_DELETED',
  MEMBERSHIP_ASSIGNED = 'MEMBERSHIP_ASSIGNED',
  MEMBERSHIP_RENEWED = 'MEMBERSHIP_RENEWED',
  MEMBERSHIP_FROZEN = 'MEMBERSHIP_FROZEN',
  MEMBERSHIP_SUSPENDED = 'MEMBERSHIP_SUSPENDED',
  MEMBERSHIP_EXPIRED = 'MEMBERSHIP_EXPIRED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  ACCESS_DISABLED = 'ACCESS_DISABLED',
  ACCESS_ENABLED = 'ACCESS_ENABLED',
  DEVICE_ADDED = 'DEVICE_ADDED',
  DEVICE_REMOVED = 'DEVICE_REMOVED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  BACKUP_CREATED = 'BACKUP_CREATED',
}
