'use client';
import { useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api/axios';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'; import { toast } from '@/components/ui/use-toast';
export default function EditUserPage() {
 const { id } = useParams<{ id: string }>(); const router = useRouter(); const [role, setRole] = useState(''); const [saving, setSaving] = useState(false);
 const { data } = useQuery({ queryKey: ['user', id], queryFn: async () => (await api.get(`/users/${id}`)).data }); const user = data?.data;
 const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { await api.patch(`/users/${id}`, { firstName: form.get('firstName'), lastName: form.get('lastName'), role: role || user.role, isActive: form.get('isActive') === 'true' }); toast({ title: 'User Updated', description: 'User details were updated.', variant: 'success' }); router.push('/settings'); } catch (error: any) { toast({ title: 'Error', description: error.response?.data?.message || 'Unable to update user.', variant: 'destructive' }); } finally { setSaving(false); } };
 if (!user) return <div className="text-white">Loading user…</div>;
 return <div className="max-w-xl space-y-6"><h1 className="text-3xl font-bold text-white">Edit User</h1><Card className="border-slate-800 bg-slate-900/50"><CardHeader><CardTitle className="text-white">User details</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><Label>First name</Label><Input name="firstName" defaultValue={user.firstName} required /></div><div><Label>Last name</Label><Input name="lastName" defaultValue={user.lastName} required /></div></div><div><Label>Email</Label><Input value={user.email} disabled /></div><div><Label>Role</Label><Select defaultValue={user.role} onValueChange={setRole}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="SUPER_ADMIN">Super Admin</SelectItem><SelectItem value="GYM_MANAGER">Gym Manager</SelectItem><SelectItem value="RECEPTIONIST">Receptionist</SelectItem></SelectContent></Select></div><div><Label>Status</Label><Select name="isActive" defaultValue={String(user.isActive)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="true">Active</SelectItem><SelectItem value="false">Inactive</SelectItem></SelectContent></Select></div><Button disabled={saving} className="bg-cyan-600">{saving ? 'Saving…' : 'Save Changes'}</Button></form></CardContent></Card></div>;
}
